Avtotest_WEB_FULLY/Controllers/ExaminationsController.cs
using Avtotest_WEB_FULLY.Models;
using Avtotest_WEB_FULLY.Repositories;
using Avtotest_WEB_FULLY.Service;
using Microsoft.AspNetCore.Mvc;

namespace Avtotest_WEB_FULLY.Controllers
{
    public class ExaminationsController : Controller
    {
     
        private QuestionRepository _questionRepository;
        private UserService _userService;
        private TicketRepository _ticketRepository;
        private int TicketQuestionCount = 20;
        public ExaminationsController()
        {
            
            _userService = new UserService();
            _questionRepository = new QuestionRepository();
            _ticketRepository = new TicketRepository();
        }

        public IActionResult Exam(int ticketid  , int? questionId, int? choiceid )
        {
            var user = _userService.GetUserFromCookies(HttpContext);
           
            if (user == null)
            {
                return RedirectToAction("SignIn", "Users");
            }
            var ticket = _ticketRepository.GetTicketById(ticketid, user.Index);
            questionId = questionId ?? ticket.FromIndex;
            if (ticket.FromIndex <= questionId && ticket.FromIndex + TicketQuestionCount > questionId)
            {
                var question = _questionRepository.GetQuestionById(questionId.Value);
                ViewBag.Ticket = ticket;
                // ticketni oldin ishlaganmi tekshirish question va ticket id orqali tabledan ticket olish
                var _choiceid = (int?)null;
                var _answer = false;
                var _ticketdata = _ticketRepository.GetTicketDatByQuestionId(ticketid, questionId.Value);
                if (_ticketdata != null)
                {
                    _answer = _ticketdata.answer;
                    _choiceid = _ticketdata.choiceid;
                }
                else if (choiceid != null)
                {
                    var ticketdata = new TicketData();
                    var answer = question.Choices.First(choice => choice.id == choiceid).Answer;
                    ticketdata.ticketid = ticketid;
                    ticketdata.questionid = questionId.Value;
                    ticketdata.choiceid = choiceid.Value;
                    ticketdata.answer = answer;
                    
                    //insert qilish
                    _ticketRepository.InsertTicketData(ticketdata:ticketdata);
                  
                    _answer = answer;
                    _choiceid = ticketdata.choiceid; }
       
                if(_answer) _ticketRepository.UpdateCorrectTicket(ticket.id);
                if (_ticketRepository.GetResponseTicketCount(ticket.id) == ticket.QuestionCount)
                    return RedirectToAction("ResultPage", new { ticketid = ticket.id });
                ViewBag.choiceid = _choiceid;
                ViewBag.Answer = _answer;
                ViewBag.TicketData = _ticketRepository.GetTicketDataById(ticketid);
                return View(question);
            }

            return NotFound();
        }


        public IActionResult ResultPage(int ticketid)
        {
            var user = _userService.GetUserFromCookies(HttpContext);
            if (user == null)
            {
                return RedirectToAction("SignIn", "Users");
            }

            var ticket = _ticketRepository.GetTicketById(ticketid, user.Index);

            return View(ticket);
        }
        public IActionResult Index()
        {
            var user = _userService.GetUserFromCookies(HttpContext);
            if (user == null)
            {
                return RedirectToAction("SignIn", "Users");
            }

            var ticket = CreateRandomTicket(user);
            return View(ticket);
        }

        private Ticket CreateRandomTicket(User user)
        { 
            var ticketcount = _questionRepository.GetQuestionCount() / TicketQuestionCount;
            var rand = new Random().Next(0, ticketcount);
            var from = TicketQuestionCount * rand;
            var ticket = new Ticket(user.Index, from, TicketQuestionCount);
            _ticketRepository.InsertTicket(ticket);
            var id = _ticketRepository.GetLastrowId();
            ticket.id = id;

            return (ticket);
        }

        public IActionResult GetQuestionByIndex(int id)
        { 
            var question = _questionRepository.GetQuestionById(id);
            return View(question);
        }
    }
}

Avtotest_WEB_FULLY/Controllers/TicketsController.cs
using Avtotest_WEB_FULLY.Models;
using Avtotest_WEB_FULLY.Repositories;
using Avtotest_WEB_FULLY.Service;
using Microsoft.AspNetCore.Mvc;

namespace Avtotest_WEB_FULLY.Controllers
{
    public class TicketsController : Controller
    {
        private TicketRepository _ticketRepository;
        private UserService _userService;

        public TicketsController()
        {
            _userService = new UserService();
            _ticketRepository = new TicketRepository();
        }

        public IActionResult Index()
        {
            var user = _userService.GetUserFromCookies(HttpContext);
            if (user == null)
            {
                return RedirectToAction("SignIn", "Users");
            }

            var tickets = _ticketRepository.GetTicketsByUserId(user.Index);

            return View(tickets);
        }

        public IActionResult Statistics()
        {
            var TicketResult = _ticketRepository.MaxCorrect();
            List<string> Name = new List<string>();
            foreach (var ticket in TicketResult)
            {
                
            }

            return View(TicketResult);
        }
    }
}

Avtotest_WEB_FULLY/Controllers/UsersController.cs
using Avtotest_WEB_FULLY.Models;
using Avtotest_WEB_FULLY.Repositories;
using Avtotest_WEB_FULLY.Service;
using Microsoft.AspNetCore.Mvc;

namespace Avtotest_WEB_FULLY.Controllers
{

    public class UsersController : Controller
    {
        private readonly UsersRepository _usersRepository;
        private readonly CookieService _cookiesService;
        private readonly UserService _userService;
        private readonly TicketRepository _ticketRepository;
        private readonly QuestionRepository _questionRepository;

        public UsersController()
        {
            _usersRepository = new UsersRepository();
            _cookiesService = new CookieService();
            _userService = new UserService();
            _ticketRepository = new TicketRepository();
            _questionRepository = new QuestionRepository();
        }

        public IActionResult Index()
        {
            var user = _userService.GetUserFromCookies(HttpContext);
            if (user != null)
            {
                return View(user);
            }

            return RedirectToAction("SignIn");
            //cookieichida user phone nomeri bormi yo'qmi tekshiradi
            //agar bo'lsa shu userni oladi va actionga jo'natadi
        }

        public IActionResult SignIn()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignIn(UserDto user)
        {
            if (!ModelState.IsValid)
            {
                return View(user);
            }

            var currentuser = _usersRepository.GetUserByPhoneNumber(user.Phone);
            if (user.Password == currentuser.Password)
            {
                _cookiesService.SendUserPhoneToCookies(currentuser.Phone!, HttpContext);
                return RedirectToAction("Index");
            }

            return RedirectToAction("SignIn");
            // userni phone si bo'yicha oladi va passwordini tekshiradi agar phone
            // va passwordi mavjud bo'lsa unga cookie beradi va index ga yuboradi
            // aks holda user qaytadan ro'yxatdan o'tishiga to'gri keladi
        }

        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignUp(User user)
        {
            
            if (!ModelState.IsValid)
            {
                return View();
            } 
            user.Image ??= "user.png";
            _usersRepository.InsertUser(user);
            _cookiesService.SendUserPhoneToCookies(user.Phone, HttpContext);
            var _user = _usersRepository.GetUserByPhoneNumber(user.Phone);
            _ticketRepository.InsertUserTicketsTraining(_user.Index, _questionRepository.GetQuestionCount() / 20, 20);
            _cookiesService.SendUserPhoneToCookies(_user.Phone, HttpContext);
            return RedirectToAction("Index");
            //userni qo'shadi va unga cookiega qiymat beradi va index ga jo'natadi   
        }

        public IActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Edit( [FromForm]Models.User user)
        {
            var _user = _userService.GetUserFromCookies(HttpContext);
            if (_user == null)
                return RedirectToAction("SignIn");


            if (!ModelState.IsValid)
                return View(user);

            _cookiesService.UpdateUserPhoneCookie(user.Phone, HttpContext);
            user.Index = _user.Index;
            user.Image = SaveImage(user.ImageFile);
            _usersRepository.UpdateUser(user);
            return RedirectToAction("Index");
        }

        private string? SaveImage(IFormFile imageFile)
        {
            if (imageFile == null)
            {
                return "user.png";
            }

            var imagePath = Guid.NewGuid().ToString("N") + Path.GetExtension(imageFile.FileName);
            var ms = new MemoryStream();
            imageFile.CopyTo(ms);
            var filePath = Path.Combine("wwwroot","Profile",imagePath);
            System.IO.File.WriteAllBytes(filePath, ms.ToArray());
            return imagePath;
        }
    }
}

Avtotest_WEB_FULLY/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Avtotest_WEB_FULLY</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Avtotest_WEB_FULLY.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Avtotest_WEB_FULLY</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a id="button" class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class = "nav-item">
                            <button class="button">   <a class="nav-link text-dark" asp-controller="Examinations" asp-action="Index">Examination</a></button>
                        </li>
                        <li class="nav-item">
                            <button class="button">  <a  class="nav-link text-dark" asp-controller="Users" asp-action="Index">Profile</a>  </button>
                        </li>
                        <li class="nav-item">
                            <button class="button">  <a class="nav-link text-dark" asp-controller="Tickets" asp-action="Index">Tickets</a>  </button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Avtotest_WEB_FULLY - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<style>
    .button {
        color: white;
        border-radius: 10px;
        border: none;
    }
    .button :hover {
            background: #005AFF;
        margin: 5px;
        margin-bottom: 5px;
        margin-left: 5px;
        margin-right:5px;
        border-radius: 10px;
    }
    .body {
        background: none;
    }
</style>